[package]
name = "noye-brain"
version = "0.1.0"
authors = ["museun <museun@outlook.com>"]

[dependencies]
regex = "1.0.1"
lazy_static = "1.0.1"
rand = "0.5.3"
tiny_http = "0.6.0"
getopts = "0.2.18"
serde = "1.0.70"
serde_derive = "1.0.70"
bincode = "1.0.1"
sysinfo = "0.5.6"
serde_json = "1.0.22"
