[package]
name = "brain"
version = "0.1.0"
edition = "2018"
authors = ["museun <museun@outlook.com>"]

[dependencies]
rand = "0.7.3"
getopts = "0.2.21"
tiny_http = "0.6.2"
serde = "1.0.104"
serde_derive = "1.0.104"
bincode = "1.2.1"
twox-hash = "1.5.0"
