[package]
name = "types"
version = "0.1.0"
authors = ["museun <museun@outlook.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.104", features = ["derive"] }
hashbrown = { version = "0.6.3", features = ["serde"] }
